# Generated by Django 6.0.1 on 2026-02-15 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_seed_skills_techstack'),
    ]

    operations = [
    ]
